[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-transaction-builder"
publish = false
version = "0.0.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
futures.workspace = true

move-binary-format.workspace = true
sui-json.workspace = true
sui-json-rpc-types.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true

move-core-types.workspace = true
