[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
edition = "2021"
license = "Apache-2.0"
name = "sui-verifier-v2"
publish = false
version = "0.1.0"

[dependencies]
move-abstract-stack.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v2/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v2" }

sui-protocol-config.workspace = true
sui-types.workspace = true
