[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-tool"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
colored.workspace = true
comfy-table.workspace = true
eyre.workspace = true
futures.workspace = true
hex.workspace = true
indicatif.workspace = true
itertools.workspace = true
move-core-types.workspace = true
num_cpus.workspace = true
object_store.workspace = true
prometheus.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tracing.workspace = true

anemo.workspace = true
anemo-cli.workspace = true
fastcrypto.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
typed-store.workspace = true

bin-version.workspace = true
sui-archival.workspace = true
sui-config.workspace = true
sui-core.workspace = true
sui-network.workspace = true
sui-package-dump.workspace = true
sui-protocol-config.workspace = true
sui-replay.workspace = true
sui-sdk.workspace = true
sui-snapshot.workspace = true
sui-storage.workspace = true
sui-types.workspace = true
