[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Print a human-readable version of Move bytecode (.mv files)"
edition = "2021"
license = "Apache-2.0"
name = "move-disassembler"
publish = false
version = "0.1.0"

[dependencies]
anyhow.workspace = true
colored.workspace = true

move-abstract-interpreter.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-coverage.workspace = true
move-ir-types.workspace = true

bcs.workspace = true
clap.workspace = true
hex.workspace = true

[features]
default = []
