[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-rosetta"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
bcs.workspace = true
clap.workspace = true
eyre.workspace = true
fastcrypto.workspace = true
futures.workspace = true
hyper.workspace = true
lru.workspace = true
mysten-metrics.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
shared-crypto.workspace = true
signature.workspace = true
strum.workspace = true
strum_macros.workspace = true
sui-config.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
sui-node.workspace = true
sui-sdk.workspace = true
sui-swarm-config.workspace = true
sui-types.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
typed-store.workspace = true

move-core-types.workspace = true

telemetry-subscribers.workspace = true

[dev-dependencies]
move-cli.workspace = true
quick-js = "0.4.1"
rand.workspace = true
reqwest.workspace = true
sui-move-build.workspace = true
sui-sdk.workspace = true
tempfile.workspace = true
test-cluster.workspace = true
