[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-transaction-checks"
publish = false
version = "0.1.0"

[dependencies]
fastcrypto-zkp.workspace = true
once_cell.workspace = true
sui-config.workspace = true
sui-execution.workspace = true
sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
tracing.workspace = true
