[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-light-client"
publish = false
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "sui-light-client"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
bytes.workspace = true
clap.workspace = true
env_logger = "0.11.5"
log = "0.4.22"
move-binary-format.workspace = true
move-core-types.workspace = true
object_store.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sui-config.workspace = true
sui-json-rpc-types.workspace = true
sui-package-resolver.workspace = true
sui-rest-api.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true
