[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-node"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
anyhow.workspace = true
arc-swap.workspace = true
axum.workspace = true
base64.workspace = true
bcs.workspace = true
bin-version.workspace = true
clap.workspace = true
futures.workspace = true
humantime.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
tap.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tracing.workspace = true
url.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-vm-profiler.workspace = true
mysten-common.workspace = true
mysten-metrics.workspace = true
mysten-network.workspace = true
mysten-service.workspace = true
narwhal-network.workspace = true
sui-archival.workspace = true
sui-config.workspace = true
sui-core.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-macros.workspace = true
sui-network.workspace = true
sui-protocol-config.workspace = true
sui-rest-api.workspace = true
sui-snapshot.workspace = true
sui-storage.workspace = true
sui-telemetry.workspace = true
sui-tls.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true
