[package]
edition = "2021"
license = "Apache-2.0"
name = "sui-single-node-benchmark"
publish = false
version.workspace = true

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
sui-config.workspace = true
sui-core = { workspace = true, features = ["test-utils"] }
sui-move-build.workspace = true
sui-storage.workspace = true
sui-test-transaction-builder.workspace = true
sui-transaction-checks.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
fs_extra.workspace = true
futures.workspace = true
once_cell.workspace = true
prometheus.workspace = true
serde = { version = "1.0.190", features = ["derive"] }
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full", "test-util", "tracing"] }
tracing.workspace = true

[dev-dependencies]
sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-simulator.workspace = true
