[package]
authors = ["Evan Chan <echan@mystenlabs.com>"]
description = "Library for common telemetry and observability functionality"
edition = "2021"
license = "Apache-2.0"
name = "telemetry-subscribers"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
version = "0.2.0"

[dependencies]
atomic_float.workspace = true
bytes.workspace = true
bytes-varint = { version = "1" }
clap.workspace = true
console-subscriber = { workspace = true, optional = true }
crossterm.workspace = true
futures.workspace = true
once_cell.workspace = true
opentelemetry = { version = "0.25.0", optional = true }
opentelemetry-otlp = { version = "0.25.0", features = [
  "grpc-tonic",
], optional = true }
opentelemetry-proto = { version = "0.25", optional = true }
opentelemetry_api = { version = "0.20.0", optional = true }
opentelemetry_sdk = { version = "0.25.0", features = [
  "rt-tokio",
], optional = true }
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry = { version = "0.26.0", optional = true }
tracing-subscriber.workspace = true

# must use same version as opentelemetry for tonic and prost, so we can't use from
# workspace
prost = "0.13"
tonic = { version = "0.12.3" }

[features]
default = ["otlp"]
otlp = [
  "opentelemetry",
  "opentelemetry-otlp",
  "opentelemetry-proto",
  "opentelemetry_api",
  "opentelemetry_sdk",
  "tracing-opentelemetry",
]
tokio-console = ["console-subscriber"]

[dev-dependencies]
camino.workspace = true
