[package]
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
license = "Apache-2.0"
name = "bytecode-verifier-transactional-tests"
publish = false
version = "0.1.0"

[dev-dependencies]
datatest-stable.workspace = true
move-transactional-test-runner.workspace = true

[[test]]
harness = false
name = "tests"

[dependencies]
