[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for sui platform"
edition = "2021"
license = "Apache-2.0"
name = "sui-move-natives-v2"
publish = false
version = "0.1.0"

[dependencies]
bcs.workspace = true
better_any.workspace = true
indexmap.workspace = true
smallvec.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true

move-stdlib-natives = { path = "../../../external-crates/move/move-execution/v2/crates/move-stdlib-natives", package = "move-stdlib-natives-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }

sui-protocol-config.workspace = true
sui-types.workspace = true
tracing.workspace = true
