[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-move"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
bin-version.workspace = true
clap.workspace = true
colored.workspace = true
once_cell = { workspace = true, optional = true }
prometheus.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-prover.workspace = true
move-unit-test.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }

move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }
sui-move-natives = { path = "../../sui-execution/latest/sui-move-natives", package = "sui-move-natives-latest" }

better_any = "0.1.1"
sui-move-build.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
rand.workspace = true
tempfile.workspace = true

move-package.workspace = true

mysten-metrics.workspace = true
sui-core.workspace = true
sui-macros.workspace = true
sui-node.workspace = true
sui-simulator.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[features]
all = ["build", "calibrate", "coverage", "disassemble", "prove", "unit_test"]
build = []
calibrate = []
coverage = []
default = []
disassemble = []
prove = []
unit_test = ["build", "dep:once_cell"]
