[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-storage"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
backoff.workspace = true
base64-url.workspace = true
bcs.workspace = true
byteorder.workspace = true
bytes.workspace = true
chrono.workspace = true
clap = "4.3.2"
fastcrypto.workspace = true
futures.workspace = true
hyper.workspace = true
hyper-rustls.workspace = true
indicatif.workspace = true
integer-encoding.workspace = true
itertools.workspace = true
moka.workspace = true
num_enum.workspace = true
object_store.workspace = true
parking_lot.workspace = true
percent-encoding = "2.2.0"
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tap.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full", "tracing"] }
tracing.workspace = true
url.workspace = true
zstd.workspace = true

eyre.workspace = true
lru.workspace = true
move-core-types.workspace = true
mysten-metrics.workspace = true
sui-config.workspace = true
sui-json-rpc-types.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
typed-store.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true

[dev-dependencies]
anyhow.workspace = true
axum.workspace = true
criterion.workspace = true
num_cpus.workspace = true
once_cell.workspace = true
pretty_assertions.workspace = true
sui-macros = { workspace = true }
sui-simulator = { workspace = true }
sui-test-transaction-builder.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true
