[package]
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "error types for typed-store crate"
edition = "2021"
license = "Apache-2.0"
name = "typed-store-error"
publish = false
version = "0.4.0"

[dependencies]
serde.workspace = true
thiserror.workspace = true
