[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-open-rpc"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
bcs.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
versions.workspace = true

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
fastcrypto = { workspace = true }
pretty_assertions.workspace = true
rand.workspace = true
sui-json.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-protocol-config.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["full"] }

move-core-types.workspace = true

[[example]]
name = "generate-json-rpc-spec"
path = "src/generate_json_rpc_spec.rs"
test = false
