[package]
edition = "2021"
name = "custom-indexer"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
prometheus = "0.13.3"
sui_data_ingestion_core = { git = "https://github.com/mystenlabs/sui", package = "sui-data-ingestion-core" }
sui_types = { git = "https://github.com/mystenlabs/sui", package = "sui-types" }
tokio = { version = "1.38.0", features = ["full"] }

[[bin]]
name = "local_reader"
path = "local_reader.rs"

[[bin]]
name = "remote_reader"
path = "remote_reader.rs"

[workspace]
