[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-package-management"
publish = false
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

sui-json-rpc-types.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true

move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
