[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Core Move execution logic"
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
name = "move-vm-runtime-v1"
publish = false
repository = "https://github.com/diem/diem"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_any.workspace = true
fail.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-bytecode-verifier = { path = "../move-bytecode-verifier", package = "move-bytecode-verifier-v1" }
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-profiler.workspace = true
move-vm-types.workspace = true

[dev-dependencies]
anyhow.workspace = true
hex.workspace = true
move-compiler.workspace = true
move-ir-compiler.workspace = true
proptest.workspace = true

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["move-vm-types/fuzzing"]
# Enable tracing and debugging also for release builds. By default, it is only enabled for debug builds.
debugging = []
gas-profiler = [
  "move-vm-config/gas-profiler",
  "move-vm-profiler/gas-profiler",
  "move-vm-types/gas-profiler",
]
lazy_natives = []
testing = []
