[package]
edition = "2021"
license = "Apache-2.0"
name = "x"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
nexlint.workspace = true
nexlint-lints.workspace = true
