[package]
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "a typed database interface"
edition = "2021"
license = "Apache-2.0"
name = "typed-store"
publish = false
repository = "https://github.com/mystenlabs/mysten-infra"
version = "0.4.0"

[dependencies]
async-trait.workspace = true
bcs.workspace = true
bincode.workspace = true
collectable.workspace = true
eyre.workspace = true
fdlimit.workspace = true
hdrhistogram.workspace = true
itertools.workspace = true
once_cell.workspace = true
ouroboros.workspace = true
prometheus.workspace = true
rand.workspace = true
rocksdb = { version = "0.21.0", default-features = false, features = [
  "lz4",
  "multi-threaded-cf",
  "snappy",
  "zlib",
  "zstd",
] }
serde.workspace = true
sui-macros.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
tracing.workspace = true
typed-store-derive = { path = "../typed-store-derive" }
typed-store-error.workspace = true
typed-store-workspace-hack = { path = "../typed-store-workspace-hack" }

[dev-dependencies]
once_cell.workspace = true
proc-macro2.workspace = true
quote.workspace = true
rand.workspace = true
rstest.workspace = true
syn.workspace = true
tempfile.workspace = true
uint.workspace = true

# Most packages should depend on sui-simulator instead of directly on msim, but for typed-store
# that creates a circular dependency.
[target.'cfg(msim)'.dependencies]
msim.workspace = true
