[package]
authors = ["Mysten Labs <build@mystenlabs.com"]
edition = "2021"
license = "Apache-2.0"
name = "sui-graphql-config"
publish = false
version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
