[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Tool to fuzz the system with randomly generated transactions"
edition = "2021"
license = "Apache-2.0"
name = "transaction-fuzzer"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]
move-core-types.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

once_cell.workspace = true
sui-core.workspace = true
sui-move-build.workspace = true
sui-protocol-config.workspace = true
sui-types = { workspace = true, features = ["fuzzing"] }


[dev-dependencies]
sui-core = { workspace = true, features = ["test-utils"] }
sui-protocol-config.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
