[package]
edition = "2024.beta"
name = "shared_no_tto"
version = "0.0.1"

[dependencies]
Sui = { local = "../../../../crates/sui-framework/packages/sui-framework" }
common = { local = "../common" }

[addresses]
shared_no_tto = "0x0"
