[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "test-cluster"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
sui-bridge.workspace = true
sui-config.workspace = true
sui-core = { workspace = true, features = ["test-utils"] }
sui-framework.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
sui-node.workspace = true
sui-protocol-config.workspace = true
sui-sdk.workspace = true
sui-swarm.workspace = true
sui-swarm-config.workspace = true
sui-test-transaction-builder.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["full", "test-util", "tracing"] }
tracing.workspace = true

move-binary-format.workspace = true

[target.'cfg(msim)'.dependencies]
fastcrypto-zkp.workspace = true
sui-simulator.workspace = true

[dev-dependencies]
sui-json-rpc-api.workspace = true
sui-macros.workspace = true
