[limits]
default-page-size = 5
max-db-query-cost = 20000
max-move-value-depth = 128
max-output-nodes = 100000
max-page-size = 10
max-query-depth = 15
max-query-nodes = 500
max-query-payload-size = 5000
max-type-argument-depth = 16
max-type-argument-width = 32
max-type-nodes = 256
request-timeout-ms = 15000
