[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Transactional tests for package upgrade compatibility checking"
edition = "2021"
license = "Apache-2.0"
name = "sui-upgrade-compatibility-transactional-tests"
publish = false
version = "0.1.0"

[dev-dependencies]
anyhow.workspace = true
datatest-stable.workspace = true
insta.workspace = true
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-package.workspace = true
sui-move-build.workspace = true

[[test]]
harness = false
name = "tests"

[dependencies]
