[package]
edition = "2024.beta"
name = "bls_signature"
version = "0.0.1"

[dependencies]
Sui = { local = "../../../../crates/sui-framework/packages/sui-framework" }

[addresses]
bls_signature = "0x0"
