[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-indexer"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
bcs.workspace = true
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
csv.workspace = true
diesel = { workspace = true, features = ["chrono", "serde_json"] }
diesel-async = { workspace = true, features = [
  "async-connection-wrapper",
  "bb8",
  "postgres",
] }
futures.workspace = true
hex.workspace = true
indicatif.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
object_store.workspace = true
prometheus.workspace = true
rand = "0.8.5"
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tap.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing.workspace = true
url.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
mysten-metrics.workspace = true
simulacrum.workspace = true
sui-archival.workspace = true
sui-config.workspace = true
sui-core.workspace = true
sui-data-ingestion-core.workspace = true
sui-json.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-open-rpc.workspace = true
sui-package-resolver.workspace = true
sui-protocol-config.workspace = true
sui-rest-api.workspace = true
sui-sdk.workspace = true
sui-snapshot.workspace = true
sui-storage.workspace = true
sui-transaction-builder.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true

cached.workspace = true
dashmap.workspace = true
diesel_migrations.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
criterion.workspace = true
ntest.workspace = true
sui-keys.workspace = true
sui-move-build.workspace = true
sui-test-transaction-builder.workspace = true
test-cluster.workspace = true

[[bin]]
name = "sui-indexer"
path = "src/main.rs"
