[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-json-rpc-api"
publish = false
version = "0.0.0"

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
jsonrpsee.workspace = true
mysten-metrics.workspace = true
once_cell.workspace = true
prometheus.workspace = true
sui-json.workspace = true
sui-json-rpc-types.workspace = true
sui-open-rpc.workspace = true
sui-open-rpc-macros.workspace = true
sui-types.workspace = true
tap.workspace = true
tracing.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the sui-sdk crate are widely used to develop on Sui and it's valuable
# to not have to pull in the entire sui repo for it.

[dev-dependencies]
