[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-rpc-loadgen"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
dashmap.workspace = true
dirs.workspace = true
futures.workspace = true
itertools.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tracing.workspace = true

shellexpand.workspace = true

serde_json.workspace = true
shared-crypto.workspace = true
strum.workspace = true
strum_macros.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
sui-sdk.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
telemetry-subscribers.workspace = true

[dev-dependencies]
test-cluster.workspace = true


[[bin]]
name = "sui-rpc-loadgen"
path = "src/main.rs"
