[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "suins-indexer"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
backoff.workspace = true
base64-url.workspace = true
bcs.workspace = true
bytes.workspace = true
diesel = { workspace = true, features = ["serde_json"] }
diesel-async = { workspace = true, features = ["bb8", "postgres"] }
dotenvy = "0.15"
futures.workspace = true
futures-util = "0.3.30"
move-core-types.workspace = true
mysten-metrics.workspace = true
mysten-service.workspace = true
notify.workspace = true
object_store.workspace = true
prometheus.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sui-data-ingestion-core.workspace = true
sui-json-rpc.workspace = true
sui-storage.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-postgres = "0.7.12"
tokio-postgres-rustls = "0.12.0"
tracing.workspace = true
url.workspace = true
webpki-roots = "0.26.3"

[dev-dependencies]
rand.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true
