[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "move-vm-profiler"
publish = false
version = "0.1.0"

[dependencies]
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

move-vm-config.workspace = true

[features]
gas-profiler = ["move-vm-config/gas-profiler"]
