[package]
authors = ["Brandon Williams <brandon@mystenlabs.com>"]
description = "tools for rustls-based certificate generation and verification"
edition = "2021"
license = "Apache-2.0"
name = "sui-tls"
publish = false
version = "0.0.0"

[dependencies]
anyhow.workspace = true
ed25519.workspace = true
pkcs8.workspace = true
rcgen.workspace = true
rustls.workspace = true
webpki.workspace = true
x509-parser.workspace = true

fastcrypto.workspace = true

# reqwest support
reqwest.workspace = true

# Axum support
axum.workspace = true
axum-server.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tower-layer.workspace = true

[dev-dependencies]
rand.workspace = true
