[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-json-rpc-tests"
publish = false
version = "0.0.0"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
move-core-types.workspace = true
move-package.workspace = true
sui-config.workspace = true
sui-core.workspace = true
sui-json.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
sui-macros.workspace = true
sui-move-build.workspace = true
sui-open-rpc.workspace = true
sui-open-rpc-macros.workspace = true
sui-protocol-config.workspace = true
sui-sdk.workspace = true
sui-simulator.workspace = true
sui-swarm-config.workspace = true
sui-test-transaction-builder.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true
test-cluster.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
