[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local sui development"
edition = "2021"
license = "Apache-2.0"
name = "sui-adapter-v1"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
serde.workspace = true
tracing.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-types.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v1/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v1" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v1/crates/move-vm-runtime", package = "move-vm-runtime-v1" }
sui-move-natives = { path = "../sui-move-natives", package = "sui-move-natives-v1" }
sui-verifier = { path = "../sui-verifier", package = "sui-verifier-v1" }

parking_lot.workspace = true
sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true

[dev-dependencies]
move-package.workspace = true

[features]
gas-profiler = [
  "move-vm-config/gas-profiler",
  "move-vm-profiler/gas-profiler",
  "move-vm-runtime/gas-profiler",
  "move-vm-types/gas-profiler",
  "sui-types/gas-profiler",
]
