[package]
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
edition = "2021"
license = "Apache-2.0"
name = "sui-transactional-test-runner"
publish = false
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
bimap.workspace = true
clap.workspace = true
criterion.workspace = true
eyre.workspace = true
futures.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true

fastcrypto.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

simulacrum.workspace = true
sui-config.workspace = true
sui-core = { workspace = true, features = ["test-utils"] }
sui-framework.workspace = true
sui-framework-snapshot.workspace = true
sui-graphql-rpc.workspace = true
sui-json-rpc.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-protocol-config.workspace = true
sui-rest-api.workspace = true
sui-storage.workspace = true
sui-swarm-config.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
