[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Package and build system for Move code"
edition = "2021"
license = "Apache-2.0"
name = "move-package"
publish = false
version = "0.1.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
itertools.workspace = true
named-lock.workspace = true
once_cell.workspace = true
petgraph.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
toml_edit.workspace = true
treeline.workspace = true
vfs.workspace = true
walkdir.workspace = true

move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-docgen.workspace = true
move-model.workspace = true
move-symbol-pool.workspace = true

whoami.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
expect-test = "1.4.0"

[[test]]
harness = false
name = "test_runner"
