[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-network"
publish = false
version = "0.0.0"

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
dashmap.workspace = true
governor.workspace = true
serde.workspace = true
shared-crypto.workspace = true
tonic.workspace = true
tower.workspace = true

sui-archival.workspace = true
sui-config.workspace = true
sui-macros.workspace = true
sui-storage.workspace = true
sui-swarm-config.workspace = true
sui-types.workspace = true

anyhow.workspace = true
arc-swap.workspace = true
bcs.workspace = true
bytes.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
futures.workspace = true
mysten-common.workspace = true
mysten-metrics.workspace = true
mysten-network.workspace = true
prometheus.workspace = true
rand.workspace = true
tap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[build-dependencies]
anemo-build.workspace = true
tonic-build.workspace = true

[dev-dependencies]
ed25519-consensus.workspace = true
sui-macros.workspace = true
telemetry-subscribers.workspace = true
tempfile = "3.3.0"
tokio = { workspace = true, features = ["test-util"] }
