[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-execution-cut"
publish = false
version = "0.1.0"

[dependencies]
anyhow.workspace = true
clap = { version = "4.3.1", features = ["derive"] }
thiserror.workspace = true
toml.workspace = true
toml_edit.workspace = true

[dev-dependencies]
expect-test.workspace = true
tempfile.workspace = true

[[bin]]
name = "cut"
path = "src/main.rs"
