[package]
edition = "2024.beta"
name = "DeepBook"
published-at = "0xdee9"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Sui = { local = "../sui-framework" }

[addresses]
deepbook = "0xdee9"
