[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem stdlib"
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
name = "move-stdlib"
publish = false
repository = "https://github.com/diem/diem"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-docgen.workspace = true
move-prover.workspace = true
# referred to via path for execution versioning
anyhow.workspace = true
hex.workspace = true
log.workspace = true
move-stdlib-natives.workspace = true
move-vm-runtime = { path = "../move-vm-runtime" }
sha2.workspace = true
walkdir.workspace = true

[dev-dependencies]
dir-diff.workspace = true
file_diff.workspace = true
move-cli.workspace = true
move-package.workspace = true
move-unit-test.workspace = true
tempfile.workspace = true

[features]
default = []
testing = []
