[package]
edition = "2024.beta"
name = "reviews_rating"
version = "0.0.1"

[dependencies]
Sui = { local = "../../../crates/sui-framework/packages/sui-framework", override = true }

[addresses]
reviews_rating = "0x0"
