[profile.default]
build_info = true
extra_output = ["storageLayout"]
ffi = true
fs_permissions = [{ access = "read", path = "/" }]
gas_reports = ["SuiBridge"]
libs = ['dependencies']
no_match_test = "testSkip"
out = 'out'
solc = "0.8.20"
src = 'contracts'
test = 'test'

[fmt]
line_length = 100

[fuzz]
runs = 1000

[rpc_endpoints]
anvil = "http://localhost:8545"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
"@openzeppelin-contracts-upgradeable" = "5.0.1"
forge-std = "1.9.2"
openzeppelin-foundry-upgrades = "0.3.1"
