[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-swarm"
publish = false
version = "0.0.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
prometheus.workspace = true
rand.workspace = true
tap.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic-health.workspace = true
tracing.workspace = true

mysten-metrics.workspace = true
mysten-network.workspace = true
sui-config.workspace = true
sui-macros.workspace = true
sui-node.workspace = true
sui-protocol-config.workspace = true
sui-swarm-config.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true
