[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem bytecode verifier tests"
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
name = "bytecode-verifier-tests-v1"
publish = false
repository = "https://github.com/diem/diem"
version = "0.1.0"

[dev-dependencies]
fail = { workspace = true, features = ["failpoints"] }
hex.workspace = true
petgraph.workspace = true

move-binary-format = { workspace = true, features = ["fuzzing"] }
# referred to via path for execution versioning
move-abstract-interpreter = { path = "../../../v2/crates/move-abstract-interpreter", package = "move-abstract-interpreter-v2" }
move-bytecode-verifier = { path = "../move-bytecode-verifier", package = "move-bytecode-verifier-v1" }
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true

[features]
fuzzing = ["move-binary-format/fuzzing"]
