[package]
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem ir to bytecode"
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
name = "move-ir-to-bytecode"
publish = false
repository = "https://github.com/diem/diem"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
codespan-reporting.workspace = true
log.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-to-bytecode-syntax.workspace = true
move-ir-types.workspace = true
move-symbol-pool.workspace = true
ouroboros.workspace = true

[features]
default = []
