[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-bridge"
publish = false
version.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bcs.workspace = true
bin-version.workspace = true
clap.workspace = true
enum_dispatch.workspace = true
ethers = "2.0"
eyre.workspace = true
fastcrypto.workspace = true
futures.workspace = true
lru.workspace = true
move-core-types.workspace = true
mysten-common.workspace = true
mysten-metrics.workspace = true
num_enum.workspace = true
once_cell.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
shared-crypto.workspace = true
sui-authority-aggregation.workspace = true
sui-config.workspace = true
sui-json-rpc-api.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
sui-sdk.workspace = true
sui-test-transaction-builder.workspace = true
sui-types.workspace = true
tap.workspace = true
telemetry-subscribers.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
typed-store.workspace = true
url.workspace = true

[dev-dependencies]
hex-literal = "0.3.4"
maplit = "1.0.2"
sui-config.workspace = true
sui-json-rpc-types = { workspace = true, features = ["test-utils"] }
sui-test-transaction-builder.workspace = true
sui-types = { workspace = true, features = ["test-utils"] }
test-cluster.workspace = true
