[package]
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "sui-swarm-config"
publish = false
version = "0.0.0"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
prometheus.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tracing.workspace = true

move-bytecode-utils.workspace = true
narwhal-config.workspace = true
shared-crypto.workspace = true
sui-config.workspace = true
sui-genesis-builder.workspace = true
sui-macros.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true

sui-execution.workspace = true
